// <auto-generated />
using bp.ot.s.API.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace bp.ot.s.API.Entities.Migrations.Dane
{
    [DbContext(typeof(OfferTransDbContextDane))]
    partial class OfferTransDbContextDaneModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bp.ot.s.API.Entities.Dane.Kontrahent.Kontrahent", b =>
                {
                    b.Property<int>("KontrahentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Imie")
                        .HasMaxLength(30);

                    b.Property<string>("NIP")
                        .HasMaxLength(12);

                    b.Property<string>("Nazwa")
                        .HasMaxLength(100);

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(50);

                    b.Property<string>("Skrot")
                        .HasMaxLength(30);

                    b.Property<string>("Uwagi");

                    b.HasKey("KontrahentId");

                    b.ToTable("Kontrahent");
                });

            modelBuilder.Entity("bp.ot.s.API.Entities.Dane.Kontrahent.KontrahentAdres", b =>
                {
                    b.Property<int>("KontrahentAdresId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDefault");

                    b.Property<string>("KodKraju")
                        .HasMaxLength(2);

                    b.Property<string>("KodPocztowy")
                        .HasMaxLength(8);

                    b.Property<int>("KontrahentRefId");

                    b.Property<string>("Miejscowosc")
                        .HasMaxLength(50);

                    b.Property<string>("TypAdresu");

                    b.Property<string>("Ulica")
                        .HasMaxLength(50);

                    b.Property<string>("UlicaNr")
                        .HasMaxLength(30);

                    b.HasKey("KontrahentAdresId");

                    b.HasIndex("KontrahentRefId");

                    b.ToTable("KontrahentAdres");
                });

            modelBuilder.Entity("bp.ot.s.API.Entities.Dane.Kontrahent.KontrahentBank", b =>
                {
                    b.Property<int>("KontrahentBankId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDefault");

                    b.Property<int>("KontrahentRefId");

                    b.Property<string>("NumerRachunku")
                        .HasMaxLength(28);

                    b.Property<string>("Swift")
                        .HasMaxLength(11);

                    b.Property<string>("Uwagi");

                    b.HasKey("KontrahentBankId");

                    b.HasIndex("KontrahentRefId");

                    b.ToTable("KontrahentBank");
                });

            modelBuilder.Entity("bp.ot.s.API.Entities.Dane.Kontrahent.KontrahentKontakt", b =>
                {
                    b.Property<int>("KontrahentId");

                    b.Property<string>("Email");

                    b.Property<string>("Fax")
                        .HasMaxLength(15);

                    b.Property<string>("Tel")
                        .HasMaxLength(15);

                    b.Property<string>("Tel2")
                        .HasMaxLength(15);

                    b.Property<string>("WWW");

                    b.HasKey("KontrahentId");

                    b.ToTable("KontrahentKontakt");
                });

            modelBuilder.Entity("bp.ot.s.API.Entities.Dane.Kontrahent.KontrahentAdres", b =>
                {
                    b.HasOne("bp.ot.s.API.Entities.Dane.Kontrahent.Kontrahent", "Kontrahent")
                        .WithMany("KontrahentAdres")
                        .HasForeignKey("KontrahentRefId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bp.ot.s.API.Entities.Dane.Kontrahent.KontrahentBank", b =>
                {
                    b.HasOne("bp.ot.s.API.Entities.Dane.Kontrahent.Kontrahent", "Kontrahent")
                        .WithMany("KontrahentBank")
                        .HasForeignKey("KontrahentRefId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bp.ot.s.API.Entities.Dane.Kontrahent.KontrahentKontakt", b =>
                {
                    b.HasOne("bp.ot.s.API.Entities.Dane.Kontrahent.Kontrahent", "Kontrahent")
                        .WithOne("KontrahentKontakt")
                        .HasForeignKey("bp.ot.s.API.Entities.Dane.Kontrahent.KontrahentKontakt", "KontrahentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
