using bp.ot.s.API.Entities.Context;
using bp.ot.s.API.Entities.Dane.Invoice;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using bp.ot.s.API.Entities.Dane.Company;
using System.Data.Common;
using System.Security.Claims;
using bp.Pomocne.DTO;
using bp.Pomocne;


namespace bp.ot.s.API.Controllers
{
    [Route("api/[controller]/[action]")]
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Finanse")]
    public class InvoiceBuyController : Controller
    {
        private readonly OfferTransDbContextDane _db;
        private CompanyService _companyService;
        private readonly InvoiceService _invoiceService;
        private readonly CommonFunctions _commonFunctions;

        public InvoiceBuyController(OfferTransDbContextDane db, CompanyService companyService, InvoiceService invoiceService, CommonFunctions commonFunctions)
        {
            this._db = db;
            this._companyService = companyService;
            this._invoiceService = invoiceService;
            this._commonFunctions = commonFunctions;
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var db = await this._invoiceService.InvoiceBuyQueryable()
                .FirstOrDefaultAsync(f=>f.InvoiceBuyId==id);

            if (db == null) {
                return NotFound();
            }

            await this._invoiceService.DeleteInvoiceBuy(id, db);
            await this._db.SaveChangesAsync();

            return NoContent();
        }

        [HttpGet("{dateStart}/{dateEnd}")]
        public async Task<IActionResult> GetAll(DateTime dateStart, DateTime dateEnd)
        {
            dateEnd = bp.Pomocne.DateHelp.DateHelpful.DateRangeDateTo(dateEnd);

            var dbResList = await this._invoiceService.InvoiceBuyQueryable()
                    .Where(w=>w.SellingDate>=dateStart && w.SellingDate<=dateEnd)
                    .OrderByDescending(o => o.InvoiceBuyId)
                    .ToListAsync();


            var res = new List<InvoiceBuyListDTO>();

            foreach (var inv in dbResList)
            {
                res.Add(this._invoiceService.InvoiceBuyDTOtoListDTO(this.EtoDTOInvoiceBuy(inv)));
            }


            return Ok(res);
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(int id)
        {

            var dbInvoice = id == 0 ? await this._invoiceService.InvoiceBuyQueryable()
                .LastOrDefaultAsync() :

                await this._invoiceService.InvoiceBuyQueryable()
                .FirstOrDefaultAsync(f=>f.InvoiceBuyId==id);

            if (dbInvoice == null) {
                return BadRequest(bp.PomocneLocal.ModelStateHelpful.ModelStateHelpful.ModelError("Błąd", $"Nie znaleziono faktury zakupu o ID: {id}"));
            }


            return Ok(this.EtoDTOInvoiceBuy(dbInvoice));
        }

        [HttpGet]
        public async Task<IActionResult> GetPaymentRemindList()
        {
            var dbRes = await this._invoiceService.InvoiceBuyQueryable()
                .Where(w => w.PaymentIsDone == false)
                .Select(s => s)
                .ToListAsync();

            var unpaid = new List<InvoicePaymentRemindDTO>();
            var notConfirmed = new List<InvoicePaymentRemindDTO>();


            foreach (var inv in dbRes)
            {
                var dto = new InvoicePaymentRemindDTO();
                this.EtDTOBasicInvoicePaymentRemind(inv, dto);

                // paymentDate based on paymentterms..
                if (inv.PaymentTerms.PaymentDays.HasValue)
                {
                    dto.PaymentDate = inv.SellingDate.AddDays(inv.PaymentTerms.PaymentDays.Value);
                }
                else {
                    dto.PaymentDate = inv.SellingDate;
                }


                //check if invoice is recived (or it its only generated by created laod-buy..)
                if (inv.InvoiceReceived)
                {
                    //dto.PaymentDate = 
                    unpaid.Add(dto);
                }
                else {
                    notConfirmed.Add(dto);
                }
            }

            var res = new
            {
                Unpaid = unpaid.OrderBy(o => o.PaymentDate).ToList(),
                NotConfirmed = notConfirmed.OrderBy(o => o.PaymentDate).ToList()
            };


            return Ok(res);
        }


        [HttpPost]
        public async Task<IActionResult> PostCalcRates([FromBody] InvoiceBuyDTO dto)
        {

            if (!ModelState.IsValid) {
                return BadRequest(ModelState);
            }

            return Ok(dto);
        }


        [HttpPut("{id}")]
        public async Task<IActionResult> Put(int id, [FromBody] InvoiceBuyDTO dto)
        {

            var dbInvoice = new InvoiceBuy();

            if (id > 0)
            {
                dbInvoice = await this._invoiceService.InvoiceBuyQueryable()
                        .FirstOrDefaultAsync(f => f.InvoiceBuyId == id);

                if (dbInvoice == null)
                {
                    return BadRequest(bp.PomocneLocal.ModelStateHelpful.ModelStateHelpful.ModelError("Błąd", $"Nie znaleziono faktury o ID: {id}"));
                }
            }

            this._invoiceService.InvoiceCommonMapper((InvoiceCommon)dbInvoice, (InvoiceCommonDTO)dto, User, dbInvoice);
            dbInvoice.CompanySeller = await this._companyService.CompanyMapper(dbInvoice.CompanySeller, dto.CompanySeller);
            if (dto.PaymentIsDone)
            {
                dbInvoice.PaymentIsDone = true;
                dbInvoice.PaymentDate = dto.PaymentDate;
            }
            else {
                dbInvoice.PaymentIsDone = false;
                dbInvoice.PaymentDate = null;
            }

            //invoiceReceived
            if (dto.IsInvoiceReceived.HasValue && dto.IsInvoiceReceived.Value==true)
            {
                dbInvoice.InvoiceReceived = true;
                dbInvoice.InvoiceReceivedDate = dto.InvoiceReceivedDate.Value;
            }
            else {
                dbInvoice.InvoiceReceived = false;
                dbInvoice.InvoiceReceivedDate = null;
            }

            //if theres no load ref invoiceRecived default is true;
            if (dbInvoice.Load == null)
            {
                dbInvoice.InvoiceReceived = true;
            }
            else {
                dbInvoice.InvoiceReceived = dto.IsInvoiceReceived.Value;
            }


            dbInvoice.SellingDate = dto.DateOfSell;

            if (id == 0) {
                this._db.Entry(dbInvoice).State = EntityState.Added;
            }

            try
            {
                await this._db.SaveChangesAsync();
            }
            catch (DbException)
            {

                throw;
            }
            return Ok(this.EtoDTOInvoiceBuy(dbInvoice));
        }



        private InvoiceBuyDTO EtoDTOInvoiceBuy(InvoiceBuy inv)
        {
            var res = new InvoiceBuyDTO();
            this._invoiceService.EtDTOInvoiceCommon((InvoiceCommon)inv, (InvoiceCommonDTO)res);
            res.InvoiceBuyId = inv.InvoiceBuyId;
            
            res.InvoiceReceivedDate = inv.InvoiceReceivedDate;
            res.IsInvoiceReceived = inv.InvoiceReceived;

            if (inv.InvoiceReceivedDate.HasValue)
            {
                res.IsInvoiceReceived = true;
                res.InvoiceReceivedDate = inv.InvoiceReceivedDate.Value;
            }
            else {
                res.InvoiceReceivedDate = null;
                res.IsInvoiceReceived = false;
            }

            if (inv.Load != null) {
                res.LoadId = inv.Load.LoadId;
                res.LoadNo = inv.Load.LoadNo;
            }
            if (inv.PaymentIsDone)
            {
                res.PaymentIsDone = true;
                res.PaymentDate = inv.PaymentDate;
            }
            else {
                res.PaymentIsDone = false;
                res.PaymentDate = null;
            }
            res.PaymentTerms = this._invoiceService.EtDTOPaymentTerms(inv.PaymentTerms);
            res.CompanySeller = _companyService.EtDTOCompany(inv.CompanySeller);
            return res;
        }

        private InvoicePaymentRemindDTO EtDTOBasicInvoicePaymentRemind(InvoiceBuy db, InvoicePaymentRemindDTO dto)
        {
            var res = dto ?? new InvoicePaymentRemindDTO();

            res.Company = this._companyService.CompanyCardMapper(db.CompanySeller);
            res.Currency = this._invoiceService.EtDTOCurrency(db.Currency);
            res.InvoiceId = db.InvoiceBuyId;
            res.InvoiceNo = db.InvoiceNo;
            //res.InvoiceTotal = this._invoiceService.EtDTOInvoiceTotal(db.InvoiceTotal);
            return res;
        }
               
    }
}
